# Generated by Django 5.1 on 2024-11-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_private_key_user_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(default='profilepictures/defaultpp.jpg', upload_to='profilepictures/'),
        ),
    ]
