# Generated by Django 5.1 on 2024-10-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
