# Generated by Django 5.1 on 2024-11-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
